/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_1;

import project_1.SandboxEngine.Window;

public class App {
    public static void main(String[] args){
        Window window = Window.create();
        window.run();
    }
}